### ISSUE TITLE
SHOWCASE /IMPACT section

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#644] opened 2020-12-20 17:34 UTC
Curated section showing data applications
![image](https://user-images.githubusercontent.com/42236514/102720025-8e786480-42e9-11eb-9cf6-cec9082d91fa.png)

Showcase section planned for COP 26. Allowing 
a) users to submit proposals for  selection/ curation 
b) where Colouring Cities academic collaborations/research applications/visualisations can be shown-
Examples of planned inclusion 

Tanikawa and Hashimoto, 2014 - material change Nagoya Japan
Aksoezen, Hassler and Kohler, 2017 - demolitions and construction Zurich 1900-2010 
London evolution animation
Clapton 4D animation

Proposed
i) Simulation of procedural Victorian house generation, and addition of 2 storeys with FR
ii) 

User needs to be able to upload brief info on data case studies relating to urban stocks : need project title, type of project, types of data used; brief description on purpose of data application, type of sector and/or academic discipline involved with tags, scale of data are, also website link and image/animation link etc.  Must include visualisations - stills, spatiotemporal, sequences, animation, simulations etc. 
System then needs to sort these and pull up visualisations relevant to any category ur searching for.

**Comment by polly64** [comment] 2021-01-23 13:31
Use of footprints r + colour means that a much wider range of audiences can provide insights into why spatial patterns exist  within data than before. e.g community planning groups and historians can explain why the same type of patterns/cycles might be happening int he same type of location over type - e.g gentrifcation cycle/burbage cycle/relationship of commercial stock with preurban network etc.

The showcase section also in some way - or perhaps in a different 'insight' section needs to courage the non technical community to take screenshots and explain why the coloured patterns look as they do

**Comment by matkoniecz** [comment] 2023-06-21 09:57
From meeting: ideally adding new entry to showcase would cause it to appear on all colouring servers

**Comment by matkoniecz** [comment] 2023-06-21 09:59
From meeting: Polly wants ability for people to submit proposed showcase entries and for someone (academic platform hosts) to review and approve entries.

**Comment by matkoniecz** [comment] 2023-06-21 10:01
> From meeting: ideally adding new entry to showcase would cause it to appear on all colouring servers

Maybe it would be stored in a separate repository? Or published on colouring server as some json file so it can be reproduced without database synchronization?

**Comment by polly64** [comment] 2023-06-29 09:45
@aldenc  linking following you comment re including GitHub repository link

**Comment by polly64** [comment] 2023-06-29 09:51
see also scivision example https://sci.vision/#/datasource-grid

**Comment by traveller195** [comment] 2023-08-02 14:55
@polly64 
@matkoniecz 
@popcorndoublefeature 
@blaumiau 
thanks for sharing your ideas!

I am not sure if I mentioned in the past that I am interest in this feature. It could be. 
Currently, it is not on priority for me. But I like the idea to share different case studies / use cases of data usage to show others how the data could be used.
Also for Colouring Dresden it could be a nice feature. But maybe later in same years, if showcases based on Dresden-related data are implemented and available. As "impact stories".


Here are other examples from the coding community. But - as I know - these pages are not open for everyone. Adding new showcases needs to request the operator of the page manually, I guess.

From OpenLayers
https://openlayers.org/en/latest/examples/

From matplotlib
https://matplotlib.org/2.0.2/gallery.html

From Jupyter Notebooks:
https://gist.github.com/ocoyawale/54d92fd4bf92508a2a6e482b5fa480fd


related to your question about having an own repository: it could make sense to divide the source code strictly from the Colouring Cities core repo.
But, for web hosting it requries an extra instance, as well. Which should be solvable for further usage. 
For example, our webpage of Colouring Dresden is made with typo3 technology. So it would not be possible to have project webpage and showcases in one prodiction environment...

just to share some thoughts

best, theodor

**Comment by polly64** [comment] 2023-08-02 15:54
hi @traveller195 @mdsimpson42 and I will begin working on this next week- do you want to have a session to chat? Just suggest any times good. It would be much better to have Turing and IOER working on this and we could also write up as another paper for discussion with @popcorndoublefeature?

We are finding that the question everyone is asking is 'how can the data be used'  what are the impacts of data release - we will therefore encourage international CCRP partners to all initially upload  as many case studies as possible - not just in relation to  colouring cities data has been used as these are still early days, but also how any of the 100 types of building attribute data we collect has been /are being used - eg building height data, building age data, building energy performance certificates, lifespan data, age etc


In the Uk we are currently trying to a build a model where voluntary regional academic hubs are set up in each country, overseeing bulk uploads and using Colouring Cities as part of their research work. Only they, other specific authorised moderators, and academic hosts, would be able to approve case studies though anyone could upload into a queue waiting for approval 

we have just released construction and technology sections today so could you let us know when Colouring Dresden in in synch

**Comment by traveller195** [comment] 2023-08-03 08:43
@polly64 @popcorndoublefeature 
interesting ideas!
My problem is, I am working currently in several projects. And I guess, I will not have much time to code on a showcase data application tool, to be honest. But we can think about the concept together in the next meeting.

another issue is, how to sync the repos with colouring-core, so that alle local repos are up to date. Unfortunately, we have no further updates since March 2023 from core repo. But on the other hand, there were a lot commits from me concerning all the translations and extensions of the platform for Dresden. 

In my opinion, it will be a bigger step (maybe in Sep or Oct) to go trouth all new commits in order to solve all rising conflicts, probable manually. 

If I see it correct, it is also an issue for most of the other local Colouring Cities projects:

![grafik](https://github.com/colouring-cities/colouring-core/assets/57902113/64d133bc-249c-4569-9431-60a621e2a533)

![grafik](https://github.com/colouring-cities/colouring-core/assets/57902113/6499cebc-2af2-4f0e-ac89-dabb34ec096e)


Thus, in the acitiviy plot for each repo, we can see that since the moment of releasing a new Colouring Cities project, the sync with core repo is not working automated any longer.

I guess, it should be well prepared to bring the versions together for all relevant commits. But there will be difference in the end: different languages, but also different features available...

best, Theodor

**Comment by polly64** [comment] 2023-08-03 10:08
@traveller195 thanks for this. @mdsimpson42 @tomalrussell could we set up a meeting about this?

**Comment by polly64** [comment] 2023-08-03 10:09
@traveller195 did you get notification this morning of updates?

**Comment by mdsimpson42** [comment] 2023-08-03 13:08
Hi

No one will get any notifications automatically at the moment. The short answer is: I haven't had a chance to look into this yet!

Users can see on their repository how far ahead/behind Colouring Core they are, and there is a button to automatically pull the changes 'downstream' from the core repo to theirs (if there are no conflicts).

[cid:574d7c11-e964-4cac-a1d3-acc6e0c0cf33]

I have a task on my list to look into automation features. I don't think we can trigger forked repos to update from the Core repo automatically or anything like that, but we may be able to send out notifications when a new pull request is merged onto the master branch. Alternatively, we may have to manually use discussions/announcements to notify all users that a major update has been released. It will still be up to them to keep their forked repositories up-to-date, however...

Also, having not managed a project on this scale before, I'm not sure how best to manage this.  I'm open to suggestions.


Thanks

Mike Simpson, PhD (he/him)
Research Software Engineer
- RSE Team<https://rse.ncldata.dev/>, Newcastle University
- Publicity co-chair #RSECon23<https://rsecon23.society-rse.org/>

***@***.******@***.***>

Please note - I am not working on Fridays during August and September.

________________________________

**Comment by polly64** [comment] 2024-01-09 13:42
see also #1233

**Closed** 2024-03-23 16:49 UTC
Labels: help wanted, priority - high
